<a href="https://colab.research.google.com/github/shubhm253/AI/blob/master/churn_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install Theano

In [0]:
!pip install tensorflow

In [0]:
!pip install keras

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
from google.colab import files
uploaded = files.upload()

In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [0]:
dataset.head(5)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [0]:
X = dataset.iloc[:,3:13].values
Y = dataset.iloc[:,13].values

In [0]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
Y

array([1, 0, 1, ..., 1, 1, 0])

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [0]:
labelencoder_x_2 = LabelEncoder()

In [0]:
X[:,2] = labelencoder_x_2.fit_transform(X[:,2])

In [0]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
labelencoder_x_1 = LabelEncoder()

In [0]:
X[:,1] = labelencoder_x_1.fit_transform(X[:,1])

In [0]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:,1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state = 42)

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:

sc =  StandardScaler()

In [0]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
classifier = Sequential()

W0730 07:18:57.772962 140016438749056 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [0]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu', input_dim = 11))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
W0730 07:19:28.695643 140016438749056 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0730 07:19:28.706117 140016438749056 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [0]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
classifier.add(Dense(output_dim = 1, init = 'uniform', activation='sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

W0730 07:19:41.731828 140016438749056 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0730 07:19:41.765207 140016438749056 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0730 07:19:41.775002 140016438749056 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [0]:
classifier.fit(X_train,Y_train,batch_size=10, epochs=100)

W0730 07:19:46.688090 140016438749056 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.4954 - acc: 0.7931
Epoch 2/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4324 - acc: 0.7945
Epoch 3/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4278 - acc: 0.7945
Epoch 4/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4235 - acc: 0.8136
Epoch 5/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4194 - acc: 0.8264
Epoch 6/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4152 - acc: 0.8315
Epoch 7/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4112 - acc: 0.8330
Epoch 8/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4086 - acc: 0.8342
Epoch 9/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4061 - acc: 0.8344
Epoch 10/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4043 - acc: 0.8342

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
y_pred = (y_pred > 0.5)

In [0]:
from sklearn.metrics import confusion_matrix

In [0]:
cm = confusion_matrix(Y_test,y_pred)

In [0]:
cm

array([[1558,   49],
       [ 224,  169]])

In [0]:
(1588+169)/2000

0.8785

In [0]:
new_prediction = classifier.predict(sc.transform(np.array([[0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))


In [0]:
new_prediction = (new_prediction > 0.5)

In [0]:
new_prediction

array([[False]])

In [0]:
#customer does not leave the bank.
#now run separately . first run till x_test and then the following one.

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier

In [0]:
from sklearn.model_selection import cross_val_score 

In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
def build_classifier():
  classifier = Sequential()
  classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu', input_dim = 11))
  classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))
  classifier.add(Dense(output_dim = 1, init = 'uniform', activation='sigmoid'))
  classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
  return classifier



In [0]:
classifier = KerasClassifier(build_classifier, batch_size=10, epochs=100)
accuracies = cross_val_score(estimator=classifier, X=X_train, y=Y_train, cv=10, n_jobs=-1)

In [0]:
accuracies

array([0.84875   , 0.85499999, 0.82625   , 0.82624999, 0.84374999,
       0.87499999, 0.84874999, 0.8125    , 0.83625   , 0.84625   ])

In [0]:
accuracies.mean()

0.8418749944865704

In [0]:
accuracies.std()

0.016641907566973896

In [0]:
#Grid Search CV

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

In [0]:
def build_classifier(optimizer):
  classifier = Sequential()
  classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu', input_dim = 11))
  classifier.add(Dense(output_dim = 6, init = 'uniform', activation='relu'))
  classifier.add(Dense(output_dim = 1, init = 'uniform', activation='sigmoid'))
  classifier.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
  return classifier

In [0]:
classifier = KerasClassifier(build_fn=build_classifier)

In [0]:
parameters = {'batch_size':[25,32], 'epochs':[100,200], 'optimizer':['adam','rmsprop']}

In [0]:
grid_search = GridSearchCV(estimator=classifier, param_grid=parameters, scoring='accuracy', cv=10)
grid_search = grid_search.fit(X_train,Y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """


Epoch 1/100
7200/7200 [==============================] - 1s 107us/step - loss: 0.5568 - acc: 0.7911
Epoch 2/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4405 - acc: 0.7933
Epoch 3/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4342 - acc: 0.7933
Epoch 4/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.4309 - acc: 0.7933
Epoch 5/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4278 - acc: 0.7933
Epoch 6/100
7200/7200 [==============================] - 0s 49us/step - loss: 0.4244 - acc: 0.7929
Epoch 7/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4219 - acc: 0.8200
Epoch 8/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4201 - acc: 0.8219
Epoch 9/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4185 - acc: 0.8250
Epoch 10/100
7200/7200 [==============================] - 0s 49us/step - loss: 0.4175 - acc: 0.8285
Epoch 11